INSERT INTO TBL_PRODUCT(PRICE, PRODUCT_NAME) VALUES(1000.00, 'Tenis');  
INSERT INTO TBL_PRODUCT(PRICE, PRODUCT_NAME) VALUES(300.00, 'Camiseta');
INSERT INTO TBL_PRODUCT(PRICE, PRODUCT_NAME) VALUES(350.00, 'Calça');
INSERT INTO TBL_PRODUCT(PRICE, PRODUCT_NAME) VALUES(150.00, 'Bagzinha');